### PR TITLE
Some steps towards fixing #19

### PR DESCRIPTION
**Pull request by zah**
Still not pretty enough in NBC. Need several improvements before we can roll it out.

image

### CODE REVIEW

**Comment by arnetheduck** [comment]
can we use some syntax like `--option        help goes here [=24]` - goes a long way towards making it less verbose

**Comment by zah** [comment]
The needed improvements are:

* Decide on what would be a good use of screen space and colors
* Deal with Nim expressions appearing in the default values
* Deal with default values that are too long (e.g. the status bar template)

Some new pragmas can be added to address these issues as a quick fix.

**Comment by arnetheduck** [comment]
I dunno - the screen shot doesn't look too bad (for long strings/expressions) but I think condensing it to a single line would do a lot - most terminals are equipped enough to line-break or do whatever users want when they encounter long lines that we don't necessarily have to repeat the work

**Comment by arnetheduck** [comment]
basically, pragmas feel like overengineering that can well be done in v2.0 when more real use cases have

**Comment by zah** [comment]
This has been rebased and merged with some additional enhancements.

**Pull request closed without merging**
